### ISSUE TITLE
Simplify transition between RxJava 1.x <-> rxAssertions <-> rxJava 2.x

### ISSUE THREAD

**Issue by MyDogTom** [ubiratansoares/rxassertions#12]
I propose to drastically change API of `rxAssertions`. I'll be happy to implement changes if you agree on them.
### Intro

After playing with `rxAssertions` I realised that transition between `RxJava 1.x` <-> `rxAssertions` <-> `rxJava 2.x` is not as smooth as it could be. Moreover, `rxAssertions` is more limited than built-in `rxJava` features.
### My understanding of `rxAssertions` purpose

Reduce the verbosity of tests by providing fluent API and removing the necessity of creating `TestSubscriber`.

In short, `rxAssertions` is just a wrapper around `rxJava` API.

Library could extend API (by introducing support for matchers, shortcuts for common operations etc) but should not reduce the functionality of `rxJava`.
### API

I've noticed that some calls have completely different naming in `rxAssertions`. As result it's hard to switch between libraries. This is significant when you are already familiar with `rxJava` syntax, work on different projects (with `rxAssertions` and without) and plan to switch to `rxJava 2.x` in the feature.
I propose to completely mimic `rxJava`. Here is a list of  examples.

| `rxJava 1.x` | `rxJava 2.x` | `rxAssertions` | to change |
| --- | --- | --- | --- |
| `assertCompleted` | `assertComplete` | `completes` |  |
| `assertNotCompleted` | `assertNotComplete` | `notCompletes` |  |
| `assertNoErrors` | `assertNoErrors` | `withoutErrors` | `noErrors` |
| `assertError(Throwable)` | `assertError(Throwable)` | `failsWithThrowable(Class)` | `error(Throwable)` |

The basic idea is to provide as similar API as possible.
### Error messages

with `rxJava 1.x`

```
    TestSubscriber<String> testSubscriber = new TestSubscriber<>();
    Observable.just("asdf").subscribe(testSubscriber);
    testSubscriber.assertNotCompleted();
```

Produces error `java.lang.AssertionError: Completed! (1 completion)`

with `rxAssertions`

```
    RxAssertions.assertThat(Observable.just("asdf"))
              .notCompletes();
```

Produces error `java.lang.AssertionError: 
Expecting null or empty but was:<[[rx.Notification@6debcae2 OnCompleted]]>`

One more example.
by `rxJava`: `java.lang.AssertionError: No errors (1 completion)`
by `rxAssertions` : `java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`

Library shouldn't modify error messages. Otherwise, we lose all improvements that are done in `rxJava`.
For additional API library should provide meaningful messages.
### Do not force towards `BlockingObservable`

Library shouldn't enforce the usage of `BlockingObservable`. 
User should explicitly choose which approach (`BlockinObservable` or `TestScheduler`) to use. See #11

**Comment by vanniktech** [comment]
As far as I see this this library won't be needed anymore for RxJava 2 as I already [stated my opinion](https://github.com/ubiratansoares/rxassertions/issues/9#issuecomment-249166002).

Built in TestSubscriber / TestScheduler are way more powerful than RxAssertions. Plus it does not make sense to have too things dangling around. Plus built in test method is a lot more convenient.

**Comment by MyDogTom** [comment]
@vanniktech That's why I think that API should be as close to `rxJava` as possible. When I will switch from `rxJava 1.x` + `rxAssertions` to `rxJava 2.0` I want to have as smooth transition as possible.

**Comment by vanniktech** [comment]
Why aren't you just using find and replace? Upgrading to RxJava 2 will anyways take some time since a lot changed

**Comment by MyDogTom** [comment]
Well, of course I can solve these difficulties in many ways. But the topic is not about how to solve them. Topic is about how not to have such difficulties at all. I believe that library can only gain from that.

**Comment by MyDogTom** [comment]
[RxJava 1.2.3](https://github.com/ReactiveX/RxJava/releases/tag/v1.2.3) covers this functionality.
> add `AssertableSubscriber` to provide method chained version of `TestSubscriber` and support a `test()` method on the base reactive classes.
