### ISSUE TITLE
Couldnt import library to my project

### ISSUE THREAD

**Issue by Zeyad-37** [ubiratansoares/rxassertions#2]
Error:Could not find com.github.ubiratansoares:rxassertions:0.2.0.
Required by:
    MyApplication:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by Zeyad-37** [comment]
i figured it out. i was putting the maven url inside the build script

**Comment by ubiratansoares** [comment]
👍
