### ISSUE TITLE
Method withFailMessage(String) missing in 0.3.1

### ISSUE THREAD

**Issue by vanniktech** [ubiratansoares/rxassertions#8]
What happened to that one?

**Comment by ubiratansoares** [comment]
We now have a more powerful mechanism to check fails powered by AssertJ Conditions. Here we have an example from library tests :

```
Condition<String> withThreeChars = new Condition<String>() {
            @Override public boolean matches(String value) {
                return value != null && value.length() == 3;
            }
        };

assertThat(values)
                .completes()
                .oneEmissionMatches(withThreeChars);
```

You can write your own Condition to check any kind of failure on terminal event as well (like HttpException from RxJavaCallAdapter with some desired status code, etc) using `failsWithCondition( )`

Does this makes sense to you?

**Comment by vanniktech** [comment]
Alright I'll give it a try though it would have been good to deprecate the method first and then remove it in a later release. And in the meanwhile in the deprecated one use the new API.

**Comment by ubiratansoares** [comment]
Yes, you are right about this. Sorry by that ... 😢 

However, give a try on Conditions : you will not regret 😄 

Best!
