### ISSUE TITLE
Support for RxJava 2.0.0

### ISSUE THREAD

**Issue by ubiratansoares** [ubiratansoares/rxassertions#9]
Since we are getting closer to RxJava 2.0.0, we must check compatibility of current implementation and offer better support for new RxJava APIs like Flowable and etc.

**Comment by vanniktech** [comment]
RC1 is already available of RxJava 2

**Comment by ubiratansoares** [comment]
Yes, I saw it this week! I`ll give a try ASAP!

**Comment by vanniktech** [comment]
To be honest after working with RxJava 2 for quite a while now I don't think this is needed any longer. All Reactive Base Types have a `test()` method where you get a TestObserver / TestSubscriber back and there you have fluent assertions available
